version: '3'

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres
    ports:
      - 5431:5432
    expose:
      - 5431
    container_name: keycloak-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: pass

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-frontend
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: pass
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres

