apiVersion: v1
kind: Service
metadata:
  labels:
    app.virciety: frontend.post
  name: frontend-post-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      targetPort: 80
      protocol: TCP
  selector:
    app.virciety: frontend.post
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.virciety: frontend.chat
  name: frontend-chat-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 80
      protocol: TCP
  selector:
    app.virciety: frontend.chat
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.virciety: frontend.event
  name: frontend-event-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5004
      targetPort: 80
      protocol: TCP
  selector:
    app.virciety: frontend.event
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.virciety: frontend.notifs
  name: frontend-notifs-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5006
      targetPort: 80
      protocol: TCP
  selector:
    app.virciety: frontend.notifs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.virciety: frontend.profile
  name: frontend-profile-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5005
      targetPort: 80
      protocol: TCP
  selector:
    app.virciety: frontend.profile
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.virciety: frontend.shell
  name: frontend-shell-svc
spec:
  type: LoadBalancer
  ports:
    - port: 4200
      targetPort: 80
      protocol: TCP
  selector:
    app.virciety: frontend.shell
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.virciety: frontend.user
  name: frontend-user-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5003
      targetPort: 80
      protocol: TCP
  selector:
    app.virciety: frontend.user
