// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePostRequest struct {
	Username    string `json:"username"`
	Description string `json:"description"`
	Data        string `json:"data"`
}

type EditPostRequest struct {
	ID             string `json:"id"`
	NewDescription string `json:"newDescription"`
}

type File struct {
	Name        string `json:"name"`
	Content     string `json:"content"`
	ContentType string `json:"contentType"`
}

type LikePostRequest struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type Post struct {
	ID          string   `json:"id"`
	Description string   `json:"description"`
	Data        *File    `json:"data"`
	Username    string   `json:"username"`
	LikedBy     []string `json:"likedBy"`
	Comments    []string `json:"comments"`
}

type RemovePostRequest struct {
	ID string `json:"id"`
}
