# use user/pass user/password credentials
version: '3.1'

services:
  comment-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: