// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Chat struct {
	WithUser string `json:"withUser"`
	Preview  string `json:"preview"`
}

type Chatroom struct {
	ID     string   `json:"id"`
	Member []string `json:"member"`
	Name   string   `json:"name"`
	Owner  string   `json:"owner"`
}

type CreateRoom struct {
	Member []string `json:"member"`
	Name   string   `json:"name"`
	Owner  string   `json:"owner"`
}

type DeleteRoom struct {
	ID       string `json:"id"`
	RoomName string `json:"roomName"`
	UserName string `json:"userName"`
}

type Dm struct {
	ChatroomID string    `json:"chatroomId"`
	CreatedAt  time.Time `json:"createdAt"`
	CreatedBy  string    `json:"createdBy"`
	ID         string    `json:"id"`
	Msg        string    `json:"msg"`
}
