// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Chat struct {
	WithUser string `json:"withUser"`
	Preview  string `json:"preview"`
}

type Chatroom struct {
	Member   []string `json:"member"`
	Messages []*Dm    `json:"messages"`
	Name     string   `json:"name"`
}

type Dm struct {
	ID        string    `json:"id"`
	Msg       string    `json:"msg"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}

type GetChatRequest struct {
	User1 string `json:"user1"`
	User2 string `json:"user2"`
}
