version: "3.2"
services:
  post-service:
    container_name: 'post-service'
    image: 'post-service'
    restart: on-failure
    build: post-service/
    ports:
      - "8083:8083"
    env_file:
      - post-service/config.env
    volumes:
      - .:/app/post-service
    depends_on:
      - rabbitmq
      - post-db
    links:
      - rabbitmq
      - post-db
    #command: ["sh", "./wait-for-it.sh", "rabbitmq:5672", "--", "./out"]
    networks:
      main:
      post:

  post-db:
    container_name: 'post-db'
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_post:/data/db
    command: mongod
    networks:
      post:

  comment-service:
    container_name: 'comment-service'
    image: 'comment-service'
    restart: on-failure
    build: comment-service/
    ports:
      - "8084:8084"
    env_file:
      - comment-service/config.env
    volumes:
      - .:/app/comment-service
    depends_on:
      - rabbitmq
      - comment-db
    links:
      - rabbitmq
      - comment-db
    networks:
      main:
      comment:

  comment-db:
    container_name: 'comment-db'
    image: mongo:latest
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_comment:/data/db
    command: mongod
    networks:
      comment:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    #restart: always
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabittmq
    networks:
      main:

  dm-service:
    container_name: 'dm-service'
    image: 'dm-service'
    restart: on-failure
    build: dm-service/
    ports:
      - "8081:8081"
    env_file:
      - dm-service/config.env
    volumes:
      - .:/app/dm-service
    depends_on:
      - rabbitmq
      - dm-db
    links:
      - rabbitmq
      - dm-db
    #command: ["sh", "./wait-for-it.sh", "rabbitmq:5672", "--", "./out"]
    networks:
      main:
      dm:

  dm-db:
    container_name: 'dm-db'
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_dm:/data/db
    command: mongod
    networks:
      dm:

volumes:
  mongodb_post:
  mongodb_comment:
  mongodb_dm:

networks:
  main:
  post:
  comment:
  dm:
