apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-post
  name: mongo-post-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-post
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-chat
  name: mongo-chat-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-chat
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-comment
  name: mongo-comment-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-comment
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-user
  name: mongo-user-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-user
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-event
  name: mongo-event-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-event
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-notifs
  name: mongo-notifs-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-notifs
status:
  loadBalancer: {}