apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-chat
  name: mongodb-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-chat
  strategy: {}
  template:
    metadata:
      labels:
        app: mongodb-chat
    spec:
      containers:
      - image: mongo
        name: mongodb-chat
        args: ["--dbpath","/data/chat-db"]
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
        volumeMounts:
        - name: "mongo-chat-data-dir"
          mountPath: "/data/chat-db"
      volumes:
      - name: "mongo-chat-data-dir"
        persistentVolumeClaim:
          claimName: "mongo-chat-data"