apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-user
  name: mongodb-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-user
  strategy: {}
  template:
    metadata:
      labels:
        app: mongodb-user
    spec:
      containers:
        - image: mongo
          name: mongodb-user
          args: ["--dbpath","/data/user-db"]
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          volumeMounts:
            - name: "mongo-user-data-dir"
              mountPath: "/data/user-db"
      volumes:
        - name: "mongo-user-data-dir"
          persistentVolumeClaim:
            claimName: "mongo-user-data"