# use user/pass user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5435:5432
    expose:
      - 5435
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - "db"
    links:
      - "db"